version: "3.2"
services:
  template-serverless-service-python:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    entrypoint: ["sh", "./docker/python/entrypoint.sh"]
    privileged: true
    stdin_open: true  # <-- Habilita entrada interativa
    tty: true         # <-- Mantém o terminal ativo
    environment:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      TEST_ENV: ${TEST_ENV}
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB: store
      DB_USER: root
      DB_PASSWORD: store
    depends_on:
      - "localstack"
      - "redis"
    ports:
      - 5001:5001
    networks:
      - service-python-v1
    volumes:
      - ./:/app
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - service-python-v1
  localstack:
    image: localstack/localstack
    privileged: true
    ports:
      - "4566:4566"
      - "4567-4582:4567-4582"
      - "9070:9070"
      - "8080:8080"
    environment:
      SERVICES: sqs,lambda,cloudwatch,s3
      DOCKER_HOST: unix:///var/run/docker.sock
      PORT_WEB_UI: 9070
      LAMBDA_EXECUTOR: local
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack
    networks:
      - service-python-v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack-data:/var/lib/localstack
networks:
  service-python-v1:
    external: true
