sonar.projectKey=madeiramadeirabr_template-serverless-service-python
sonar.organization=madeiramadeirabr
sonar.sources=.
sonar.exclusions=vendor/**,coverage/**,bin/**/*,libs/**,build/**,.chalice/**/*,.idea/**,bin/**,node/**,tests/**/*,test/**,tmp/**,dist/**,scripts/**/*,target/**/*,vendor/**/*,.devops/**/*,docker/**/*,samples/**/*,.vscode/**,.git/**
sonar.python.version=3.8
sonar.tests=tests
sonar.tests.inclusions=**/test_*.py
sonar.python.file.suffixes=py
sonar.python.coverage.reportPaths=target/component/report.xml,target/unit/report.xml
sonar.junit.reportsPath=target/unit/junit-report.xml