servers:
- url: null
  description: null
- url: http://localhost:5000
  description: Development server
paths:
  /alive:
    get:
      summary: Service Health Method
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
        '424':
          description: Failed dependency response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
        '503':
          description: Service unavailable response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
  /v1/product:
    get:
      summary: Product List
      parameters:
      - name: limit
        in: query
        description: List limit
        required: false
        schema:
          type: int
          example: 20
      - name: offset
        in: query
        description: List offset
        required: false
        schema:
          type: int
          example: 0
      - name: fields
        in: query
        description: Filter fields with comma
        required: false
        schema:
          type: string
          example: null
      - name: order_by
        in: query
        description: Ordination of list
        required: false
        schema:
          type: string
          enum:
          - asc
          - desc
      - name: sort_by
        in: query
        description: Sorting of the list
        required: false
        schema:
          type: string
          example: id
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HateosProductListResponse'
        4xx:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListErrorResponse'
        5xx:
          description: Service fail response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListErrorResponse'
    post:
      summary: Product Create
      requestBody:
        description: Product to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateRequest'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreateResponse'
        4xx:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreateErrorResponse'
        5xx:
          description: Service fail response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreateErrorResponse'
  /v1/product/{uuid}:
    get:
      summary: Product Get
      parameters:
      - in: path
        name: uuid
        description: Product Id
        required: true
        schema:
          type: string
          format: uuid
          example: 4bcad46b-6978-488f-8153-1c49f8a45244
      - name: fields
        in: query
        description: Filter fields with comma
        required: false
        schema:
          type: string
          example: null
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HateosProductGetResponse'
        4xx:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductGetErrorResponse'
        5xx:
          description: Service fail response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductGetErrorResponse'
    put:
      summary: Complete Product Update
      parameters:
      - in: path
        name: uuid
        description: Product Id
        required: true
        schema:
          type: string
          format: uuid
          example: 4bcad46b-6978-488f-8153-1c49f8a45244
      requestBody:
        description: Product to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCompleteUpdateRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdateResponse'
        4xx:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdateErrorResponse'
        5xx:
          description: Service fail response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdateErrorResponse'
    patch:
      summary: Soft Product Update
      parameters:
      - in: path
        name: uuid
        description: Product Id
        required: true
        schema:
          type: string
          format: uuid
          example: 4bcad46b-6978-488f-8153-1c49f8a45244
      requestBody:
        description: Product field to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductSoftUpdateRequest'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdateResponse'
        4xx:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdateErrorResponse'
        5xx:
          description: Service fail response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdateErrorResponse'
    delete:
      summary: Soft Product Delete
      parameters:
      - in: path
        name: uuid
        description: Product Id
        required: true
        schema:
          type: string
          format: uuid
          example: 4bcad46b-6978-488f-8153-1c49f8a45244
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSoftDeleteResponse'
        4xx:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSoftDeleteErrorResponse'
        5xx:
          description: Service fail response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSoftDeleteErrorResponse'
info:
  title: template-serverless-service-python
  version: 1.0.2
openapi: 3.0.2
components:
  schemas:
    Entry:
      type: object
      properties:
        status:
          type: string
          example: healthy
        duration:
          type: string
          example: '0:00:00.013737'
        tags:
          type: array
          items:
            type: string
            example: db
    EntryData:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Entry'
    HealthCheck:
      type: object
      properties:
        status:
          type: string
          example: healthy
        total_duration:
          type: string
          example: '0:00:00.013737'
        entries:
          $ref: '#/components/schemas/EntryData'
    Meta:
      type: object
      properties:
        href:
          type: string
          format: url
        next:
          type: string
          format: url
        previous:
          type: string
          format: url
        first:
          type: string
          format: url
        last:
          type: string
          format: url
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        sku:
          type: integer
          example: 657705
        name:
          type: string
          example: "Guarda Roupa Casal com Espelho 3 Portas de Correr Lara Espresso\
            \ M\xF3veis"
        description:
          type: string
          example: "Guarda Roupa com maior resist\xEAncia, durabilidade e acabamento,\
            \ revestimento interno e externo. Pintura em estufas modernas com UV (ultra\
            \ violeta). Modelo com corredi\xE7a met\xE1lica em a\xE7o, 4 gavetas espa\xE7\
            osas, perfil em alum\xEDnio, roldanas de a\xE7o carbono com rolamento,\
            \ divis\xE3o ele/ela"
        supplier_id:
          type: integer
          example: 1
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
        active:
          type: integer
          enum:
          - 0
          - 1
        uuid:
          type: string
          format: uuid
          example: 4bcad46b-6978-488f-8153-1c49f8a45244
    RequestControl:
      type: object
      properties:
        offset:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        count:
          type: integer
      required:
      - limit
    HateosProductListResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        code:
          type: integer
          example: 1
        label:
          type: string
          example: common.success
        message:
          type: string
          example: Success
        params:
          type: array
          items:
            type: string
        meta:
          $ref: '#/components/schemas/Meta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        control:
          $ref: '#/components/schemas/RequestControl'
      required:
      - code
    ProductListErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 11
        label:
          type: string
          example: common.error.list_error
        message:
          type: string
          example: Unable to return the list data, please review your request
        params:
          type: array
          items:
            type: string
        details:
          type: string
        trace:
          type: string
      required:
      - code
    Link:
      type: object
      properties:
        href:
          type: string
        rel:
          type: string
        method:
          type: string
    HateosProductGetResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        code:
          type: integer
          example: 1
        label:
          type: string
          example: common.success
        message:
          type: string
          example: Success
        params:
          type: array
          items:
            type: string
        meta:
          $ref: '#/components/schemas/Meta'
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        data:
          $ref: '#/components/schemas/Product'
      required:
      - code
    ProductGetErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 14
        label:
          type: string
          example: common.error.find_error
        message:
          type: string
          example: Unable to find the record
        params:
          type: array
          items:
            type: string
        details:
          type: string
        trace:
          type: string
      required:
      - code
    ProductCreateRequest:
      type: object
      properties:
        sku:
          type: integer
          example: 657705
        name:
          type: string
          example: "Guarda Roupa Casal com Espelho 3 Portas de Correr Lara Espresso\
            \ M\xF3veis"
        description:
          type: string
          example: "Guarda Roupa com maior resist\xEAncia, durabilidade e acabamento,\
            \ revestimento interno e externo. Pintura em estufas modernas com UV (ultra\
            \ violeta). Modelo com corredi\xE7a met\xE1lica em a\xE7o, 4 gavetas espa\xE7\
            osas, perfil em alum\xEDnio, roldanas de a\xE7o carbono com rolamento,\
            \ divis\xE3o ele/ela"
        supplier_id:
          type: integer
          example: 1
        active:
          type: integer
          enum:
          - 0
          - 1
    ProductCreateResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        code:
          type: integer
          example: 1
        label:
          type: string
          example: common.success
        message:
          type: string
          example: Success
        params:
          type: array
          items:
            type: string
        data:
          $ref: '#/components/schemas/Product'
      required:
      - code
    ProductCreateErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 17
        label:
          type: string
          example: common.error.create_error
        message:
          type: string
          example: Unable to create the record
        params:
          type: array
          items:
            type: string
        details:
          type: string
        trace:
          type: string
      required:
      - code
    ProductCompleteUpdateRequest:
      type: object
      properties:
        sku:
          type: integer
          example: 657705
        name:
          type: string
          example: "Guarda Roupa Casal com Espelho 3 Portas de Correr Lara Espresso\
            \ M\xF3veis"
        description:
          type: string
          example: "Guarda Roupa com maior resist\xEAncia, durabilidade e acabamento,\
            \ revestimento interno e externo. Pintura em estufas modernas com UV (ultra\
            \ violeta). Modelo com corredi\xE7a met\xE1lica em a\xE7o, 4 gavetas espa\xE7\
            osas, perfil em alum\xEDnio, roldanas de a\xE7o carbono com rolamento,\
            \ divis\xE3o ele/ela"
        supplier_id:
          type: integer
          example: 1
        active:
          type: integer
          enum:
          - 0
          - 1
    ProductUpdateResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        code:
          type: integer
          example: 1
        label:
          type: string
          example: common.success
        message:
          type: string
          example: Success
        params:
          type: array
          items:
            type: string
        data:
          $ref: '#/components/schemas/Product'
      required:
      - code
    ProductUpdateErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 18
        label:
          type: string
          example: common.error.update_error
        message:
          type: string
          example: Unable to update the record
        params:
          type: array
          items:
            type: string
        details:
          type: string
        trace:
          type: string
      required:
      - code
    ProductSoftUpdateRequest:
      type: object
      properties:
        field:
          type: string
          example: value
    ProductSoftDeleteResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        code:
          type: integer
          example: 1
        label:
          type: string
          example: common.success
        message:
          type: string
          example: Success
        params:
          type: array
          items:
            type: string
        data:
          type: object
          example:
            deleted: true
      required:
      - code
    ProductSoftDeleteErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        code:
          type: integer
          example: 18
        label:
          type: string
          example: common.error.update_error
        message:
          type: string
          example: Unable to update the record
        params:
          type: array
          items:
            type: string
        details:
          type: string
        trace:
          type: string
      required:
      - code
